from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('auth/login/', views.auth_login, name='auth_login'),
    path('auth/logout/', views.auth_logout, name='auth_logout'),
    path('manage/products/page/', views.manage_products_page, name='manage_products_page'),
    path('manage/sales/page/', views.manage_sales_page, name='manage_sales_page'),
    path('manage/reports/page/', views.manage_reports_page, name='manage_reports_page'),
    path('manage/reports/export-pdf/', views.manage_reports_export_pdf, name='manage_reports_export_pdf'),
    path('manage/audit/page/', views.manage_audit_page, name='manage_audit_page'),
    path('manage/sales/create/', views.manage_sales_create_order, name='manage_sales_create_order'),
    path('manage/sales/mark-paid/<int:order_id>/', views.manage_sales_mark_paid, name='manage_sales_mark_paid'),
    path('manage/orders/print/<int:order_id>/', views.manage_order_print_page, name='manage_order_print_page'),
    path('manage/products/page/save/', views.manage_products_save_page, name='manage_products_save_page'),
    path('manage/products/page/delete/<int:product_id>/', views.manage_products_delete_page, name='manage_products_delete_page'),
    path('manage/orders/page/delivery/<int:order_id>/', views.manage_order_delivery_page, name='manage_order_delivery_page'),
    path('manage/orders/page/mark-all-paid/', views.manage_orders_mark_all_paid_page, name='manage_orders_mark_all_paid_page'),
    path('manage/orders/page/manual-create/', views.manage_order_manual_create_page, name='manage_order_manual_create_page'),
    path('manage/orders/page/delete/<int:order_id>/', views.manage_order_delete_page, name='manage_order_delete_page'),
    path('manage/users/page/create/', views.manage_users_create_page, name='manage_users_create_page'),
    path('manage/costs/page/create/', views.manage_costs_create_page, name='manage_costs_create_page'),
    path('manage/costs/page/delete/<int:cost_id>/', views.manage_costs_delete_page, name='manage_costs_delete_page'),
    path('manage/whatsapp/page/create/', views.manage_whatsapp_recipient_create_page, name='manage_whatsapp_recipient_create_page'),
    path('manage/whatsapp/page/delete/<int:recipient_id>/', views.manage_whatsapp_recipient_delete_page, name='manage_whatsapp_recipient_delete_page'),
    path('manage/products/', views.product_manage_list, name='product_manage_list'),
    path('manage/products/save/', views.product_manage_save, name='product_manage_save'),
    path('manage/products/delete/<int:product_id>/', views.product_manage_delete, name='product_manage_delete'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/update/<int:product_id>/', views.cart_update, name='cart_update'),
    path('checkout/finalize/', views.checkout_finalize, name='checkout_finalize'),
    path('checkout/status/<int:order_id>/', views.checkout_status, name='checkout_status'),
    path('payments/webhook/', views.payments_webhook, name='payments_webhook'),
    path('orders/print/<int:order_id>/', views.order_print_public_page, name='order_print_public_page'),
]
