# Generated by Django 5.2.11 on 2026-02-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('whatsapp', models.CharField(max_length=25)),
                ('payment_method', models.CharField(choices=[('pix', 'Pix')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pix_code', models.TextField()),
                ('items_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
