# Generated by Django 5.2.11 on 2026-02-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_is_paid_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_external_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_status_detail',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
