# Generated by Django 5.2.11 on 2026-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_whatsapprecipient_order_whatsapp_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('card', 'Cartao'), ('cash', 'Dinheiro')], max_length=10),
        ),
    ]
