# Generated by Django 5.2.11 on 2026-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_created_by_staff_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_file', models.ImageField(blank=True, null=True, upload_to='costs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
