# Generated by Django 5.2.11 on 2026-03-08 04:05

import django.db.models.deletion
from django.db import migrations, models


def seed_existing_profit_distribution_entries(apps, schema_editor):
    ProfitDistributionPerson = apps.get_model('shop', 'ProfitDistributionPerson')
    ProfitDistributionEntry = apps.get_model('shop', 'ProfitDistributionEntry')

    for person in ProfitDistributionPerson.objects.exclude(amount=0):
        ProfitDistributionEntry.objects.create(
            person_id=person.id,
            amount=person.amount,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_profitdistributionconfig_profitdistributionperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDistributionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shop.profitdistributionperson')),
            ],
            options={
                'verbose_name': 'Lancamento da distribuicao de lucro',
                'verbose_name_plural': 'Lancamentos da distribuicao de lucro',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(seed_existing_profit_distribution_entries, noop_reverse),
    ]
